### PR TITLE
Add static url source (Requires #145)

### LINKED ISSUE #67: Add simple URL source for images
I found out about this GOES satelite that generates new images every 10 minutes of various parts of the globe (and the full disk).  They don't seem to have a json file available, but they do update a static URL with a new image.  So it would be great if I could just point to a URL and have it auto-refresh a new image.

The json to make this work is:
```
{
    "url": "https://cdn.star.nesdis.noaa.gov/GOES16/ABI/FD/GEOCOLOR/1808x1808.jpg"
}
```
with a key of `$.url`.

I was able to get this to work by uploading this json file to a publically accessible web page, but it would be neat to just be able to point to the URL itself.

### PR DESCRIPTION
**Pull request by Lucki**
I added a simple URL source which fixes #67

### CODE REVIEW

**Review by ifl0w — APPROVED** [review]
Nothing to complain about here! :smile: Thanks for adding this source.

Out of curiosity (and maybe adding them to the wiki as examples), which APIs did you find/use that use a static URL and return a random image?

**Comment by ifl0w** [comment]
Ah, of course, and as always, please rebase. Again sorry for the unnecessary hassle.

**Comment by ifl0w** [comment]
> Out of curiosity (and maybe adding them to the wiki as examples), which APIs did you find/use that use a static URL and return a random image?

Or was that only for the referenced issue?

**Comment by Lucki** [comment]
> > Out of curiosity (and maybe adding them to the wiki as examples), which APIs did you find/use that use a static URL and return a random image?
> 
> Or was that only for the referenced issue?

Only for the referenced image, haven't tested for other services.
With the splitted adapter layout and the blueprint it was really easy to do.

**Pull request merged**
