### PR TITLE
Source Config Modal

### PR DESCRIPTION
**Pull request by ifl0w**

### CODE REVIEW

**Comment by ifl0w** [comment]
@Lucki Thanks for testing! Might be non-standard icons. Haven't checked that TBH. Do you know where the icons are installed to or have a list of valid icons to use?

Other than that, are you okay with the changes? :)

💯 TS and blueprints are massive improvements to the workflow! Definitely reducing friction for making any changes.

**Comment by ifl0w** [comment]
The icon also didn't show for me :o ... Somehow, I forgot to change it to some working icon :D So, thanks for reporting!

I now just used a plus sign that I found under `/usr/share/icons/Adwaita/`. I assume those are all available in the settings UI by default. At least they also work in the Ubuntu container.

**Comment by Lucki** [comment]
I don't know anymore where I looked for them, sry.

My UI draft was more cluttered, definitely an improvement with this.
Only thing I see is that the type combo and name input has a strange height compared to everything else:
image

**Comment by ifl0w** [comment]
Yeah, I am also not 100% happy with how the source type selection and name input looks. It was just what I could get working quickly. Probably should try to improve it a little. But I guess this is okay for now..

The search was just a feature I saw in the TS types. I didn't really look into if it can be customized easily.

**Comment by ifl0w** [comment]
Not sure if these options are any better :sweat_smile: ... but those are the low effort ones.
The first uses only the adw elements the other two only gtk. 

Screenshot 1

Screenshot 2

Screenshot 3

**Comment by Lucki** [comment]
Yea, we should stick with the first try for now.

**Pull request merged**
