### PR TITLE
Fixed the HTTPS issue in URL

### PR DESCRIPTION
**Pull request by pranav08**
Issue was observed while following steps from READMe.md file. I have changed the URL to one which works.

### CODE REVIEW

**Comment by ifl0w** [comment]
Can you provide a screenshot or the log of the error? Both clone commands should work properly.
Did you setup a ssh key for your GitHub account?

Probably all clone URLs should be removed from the README.md since they could changne and the users should know how to clone on their own.

**Comment by pranav08** [comment]
I did not setup the ssh key for github account because I simply wanted to download and setup RandomWallpaper in my friend's laptop. After following the README.md file, I got into below error:

randomwallpaper

Maybe few other people would have faced the same problem and left right there. After some experimentation, I could clone it on the basis of URL.

**Comment by ifl0w** [comment]
Yeah, that error occurred because you need to set up a ssh key to be able to clone from GitHub with the command that I used in the readme. The extension also can be easily installed from [extensions.gnome.org](https://extensions.gnome.org/extension/1040/random-wallpaper/) if your gnome installation is configured for the website.

I'll not merge this pull request since it is not the correct solution for this issue and the instruction should be updated accordingly.

I really appreciate your help and I'll update the readme with the next update.
Thank you for your support!

**Comment by pranav08** [comment]
HI there,

Thanks for your reply. I have 4-5 years of experience in many technology
stacks. I wish to contribute to your open source projects through github?
Is there any feature, bug or change that I could try working on?
I would be happy to help!

Regards,
Pranav Nandan

**Comment by ifl0w** [comment]
Hey, that sounds great! You can just take on one of the Issues in the issue list or open a new issue with your own idea to discuss how to implement it. Just use the issue feature to communicate for now. :)

A good start would be to roughly read through the code to get an idea of the current state and then to implement or to fix one of the smaller issues like #25, #30 or #33.

There is also a lot of code formatting, refactoring and documentation to do in this project since I basically have been the only contributor to this project and there are a lot of things that could be implemented way better.

**Pull request closed without merging**
