### PR TITLE
Replace gi-types with girs and small cosmetic changes

### PR DESCRIPTION
**Pull request by ifl0w**
The main change in this PR is the replacement of gi-types with the girs type definitions. This is done because gi-types wasn't updated in quite some time and does not include all newer type definitions.

### CODE REVIEW

**Comment by ifl0w** [comment]
@Lucki Do you see any significant issue with the switch to the girs definitions? Can you also give the
[Reset auto-fetch timer after manual refresh](https://github.com/ifl0w/RandomWallpaperGnome3/pull/183/commits/4b9cf5937cc0c8f737d61b2ae537471b6d997ba2) commit a sanity check?

**Comment by ifl0w** [comment]
Improved the workarounds required for using girs instead of gi-types.

**Comment by Lucki** [comment]
> Do you see any significant issue with the switch to the girs definitions?

No, those I used were from one of the maintainers of GJS and hoped they would be somewhat up-to-date…
You might want to follow https://gitlab.gnome.org/GNOME/gjs/-/issues/521 to stay tuned.

> [Reset auto-fetch timer after manual refresh](https://github.com/ifl0w/RandomWallpaperGnome3/pull/183/commits/4b9cf5937cc0c8f737d61b2ae537471b6d997ba2) commit a sanity check?

The name is a bit stupid but `_reset()` sets the last activation time to `date.now()`. With your change that's always happening and not only when no last activation was happening - resulting in the `if (intervalSurpassed) {` check never triggering.

**Comment by ifl0w** [comment]
Thanks for the feedback and the reference to the issue!

I just dropped the commit regarding the timer. It is not really important to me, and we can always revisit it later in case someone doesn't like the new behavior.

**Pull request merged**
