### PR TITLE
Add Reddit support

### PR DESCRIPTION
**Pull request by oskarkook**
Adds support for fetching wallpapers from Reddit. Reddit has cool subreddits for wallpapers & other images.

Implementation note: we use the preview image that Reddit generates, as this is the easiest image to fetch without having to do our own validation & resizing etc. Maybe in the future this can be improved.

wallpapers

### CODE REVIEW

**Comment by ifl0w** [comment]
First of all, this implementation looks pretty solid! :tada: 

It would have been possible to use the generic JSON source for this, but, I guess, this solution is more convenient anyway.

What is the difference between the `data.preview.images[0].sources.url` and the `data.url` images in the reddit response?

And I do not fully understand your implementation note. What would have been the alternative to this implementation and what would have been the advantages?

I really appreciate your submission! I'll test and merge it as soon as possible and go through the descriptions in the interface to adapt them to this new feature.

**Comment by oskarkook** [comment]
I used the generic one, but I'm not sure if you can filter for SFW with that. Maybe there's some query param that can be flipped for that, but I had a hard time finding documentation for the API.

Reddit caches its own preview image from the source image - the actual source itself is `data.url` as you pointed out. I initially opted for preview as otherwise you'd have to write some extra code for cases like https://imgur.com/6BouZGr where the user did not link to the actual image but to some "wrapper" of it (but Reddit still knows how to generate a preview from it). However, looking into it now, I think those are already filtered out with `data.post_hint !== 'image'`, so that criteria probably doesn't even matter anymore. I don't have time to test right now whether there would be any problems with going to the source directly instead of fetching the Reddit preview.

**Comment by ifl0w** [comment]
Ok, I understand your decisions.

I think that the `preview` is the correct way to go since you cannot implement a solution that supports all possible websites that could potentially be linked on Reddit.

The only question remaining is if we should filter with the `post_hint` since it reduces the set of images. On the other hand, I do not know if it is guaranteed, that there is always a valid preview member.

I'd be ok with the current implementation.

**Comment by ifl0w** [comment]
I'll only go through some of the strings and probably link back to the Reddit post instead of the media file.
Well done!

**Pull request merged**
