### PR TITLE
Backport latest commits to gnome-shell-legacy

### PR DESCRIPTION
**Pull request by pascallj**
Backporting was not that difficult after all. Carefully checked each commit for breaking changes, but the new lay-out is still compatible with GTK3.

I backported/cherry-picked each individual commit for completeness, but in the end this results in this diff between this updated branch and master:
```diff
diff --git a/randomwallpaper@iflow.space/metadata.json b/randomwallpaper@iflow.space/metadata.json
index e3a7a77..cc4d7f3 100644
--- a/randomwallpaper@iflow.space/metadata.json
+++ b/randomwallpaper@iflow.space/metadata.json
@@ -1,5 +1,8 @@
 {
-  "shell-version": [ "40", "40.0", "40.1" ],
+  "shell-version": [
+    "3.36",
+    "3.38"
+  ],
   "uuid": "randomwallpaper@iflow.space",
   "settings-schema": "org.gnome.shell.extensions.space.iflow.randomwallpaper",
   "name": "Random Wallpaper",
diff --git a/randomwallpaper@iflow.space/prefs.js b/randomwallpaper@iflow.space/prefs.js
index c2ed01a..3162be8 100644
--- a/randomwallpaper@iflow.space/prefs.js
+++ b/randomwallpaper@iflow.space/prefs.js
@@ -23,7 +23,7 @@ function init(metaData) {
 function buildPrefsWidget() {
 	let settings = new RandomWallpaperSettings();
 	let widget = settings.widget;
-	widget.show();
+	widget.show_all();
 
 	return widget;
 }
@@ -34,6 +34,8 @@ var RandomWallpaperSettings = class {
 	constructor() {
 		this.logger = new LoggerModule.Logger('RWG3', 'RandomWallpaper.Settings');
 
+		this.currentSourceSettingsWidget = null;
+
 		this._wallpaperController = null;
 
 		this._settings = Convenience.getSettings(RWG_SETTINGS_SCHEMA);
@@ -94,8 +96,13 @@ var RandomWallpaperSettings = class {
 					break;
 			}
 
+			if (this.currentSourceSettingsWidget !== null) {
+				container.remove(this.currentSourceSettingsWidget);
+			}
+
 			if (targetWidget !== null) {
-				container.set_child(targetWidget);
+				this.currentSourceSettingsWidget = targetWidget;
+				container.add(this.currentSourceSettingsWidget);
 			}
 		});
 
```

### CODE REVIEW

**Comment by pascallj** [comment]
To keep better track of commits, I've updated it to now use a merge instead of cherry-picks. Although this introduces a lot more merge commits in this PR, it will be more in line with the master branch and only introduce two 'new' commits.

For the cherry-picked version: https://github.com/pascallj/RandomWallpaperGnome3/tree/gnome-shell-legacy-cherry

**Comment by ifl0w** [comment]
That again is some great work! Thanks for the backport!

@pascallj I just tested it with your container solution but I guess we can not verify that it works for gnome-shell 3.34? So should we drop it from the meta for the next release?

**Review by ifl0w — APPROVED** [review]

**Comment by pascallj** [comment]
Your welcome. Thank you for the extension in general. I've been using it for years now.

It depends on which version you want to support and why. I guess there are valid reasons for supporting 3.36, 3.38 and 40 as they are still in use by respectively Ubuntu 20.04 LTS, 21.04 and 21.10. Similar for Debian of course. If support for Ubuntu 18.04 LTS is also desired, we should even go back as far as 3.28. I don't know if there are any other major distributions using older versions which are worth supporting.

**Comment by ifl0w** [comment]
Then I'll drop the support for 3.34. I don't think releasing for untested systems is a good idea and older releases might still work for old versions.

**Pull request merged**
