### PR TITLE
v3.0.0 Release Preparations

### PR DESCRIPTION
**Pull request by ifl0w**
Collecting a few minor changes in preparation for the finalization of 3.0.0 in this PR.

### CODE REVIEW

**Comment by Lucki** [comment]
The installation instructions could mention the nightly builds with the `gnome-extensions install $zip` command as an alternative to the git+build+symlink flow.

**Comment by ifl0w** [comment]
Mentioning the install command is a good idea! With nightly builds, you mean the builds from the GitHub worker, I guess?

**Comment by Lucki** [comment]
Yes :ok_hand:

**Comment by ifl0w** [comment]
> Maybe it's possible to link the latest artifact for a branch

TBH, I don't want to directly link artifacts from a runner as long as the runner uses the updated libs from a newer ubuntu version.

**Pull request merged**
